version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mysql
      - mongo
      - redis

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  migrate:
    image: migrate/migrate
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
    entrypoint:
      - sh
      - -c
      - |
        migrate -path=/migrations \
                -database "mysql://${MYSQL_USER_NAME}:${MYSQL_PASSWORD}@tcp(${MYSQL_URL})/${MYSQL_DATABASE_NAME}" up
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
  mongo_data:
  redis_data:
